name: Send Email Notification

on:
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        if: github.event.pull_request.merged == true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Branch Merge Notification for Test-repo"
          to: sanafarooque2604@gmail.com
          from: sanafarooque26@gmail.com
          body: "Branch '${{ github.event.pull_request.head.ref }}' was merged into '${{ github.event.pull_request.base.ref }}' by ${{ github.actor }}"
