name: Notify Teams on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true   # Only if actually merged
    runs-on: ubuntu-latest
    steps:
      - name: Send MS Teams notification
        uses: neonidian/teams-notify-build-status@v4
        with:
          webhookUrl: ${{ secrets.MS_TEAMS_WEBHOOK }}
          title: "✅ Pull Request Merged"
          titleBackgroundColor: "green"
          message: |
             **Repository:** ${{ github.repository }}
            
             **PR:** [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) - ${{ github.event.pull_request.title }}
            
             **Author:** ${{ github.event.pull_request.user.login }}
            
             **Merged by:** ${{ github.event.pull_request.merged_by.login }}

            

